---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-dev-deployment
  namespace: rdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: to-do-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      containers:
      - name: to-do-app
        image: berktugsnbck/react-app:v$DOCKER_BUILD_NUMBER
        ports:
          - containerPort: 3000
