---
apiVersion: v1
kind: Service
metadata:
  name: todoapp-dev-service
  namespace: rdev
spec:
  type: NodePort
  selector:
    app: to-do-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000
    protocol: TCP
