---
apiVersion: v1
kind: Service
metadata:
  name: todoapp-rtest-service
  namespace: rtest
spec:
  type: NodePort
  selector:
    app: to-do-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32000
    protocol: TCP

